packages:
  - apps/*
  - packages/*

catalog:
  '@sveltejs/adapter-vercel': ^6.3.0
  '@sveltejs/kit': ^2.15.0
  '@sveltejs/vite-plugin-svelte': ^5.0.0
  '@vercel/edge-config': ^1.4.0
  '@vercel/functions': ^3.3.0
  '@vercel/otel': ^2.1.0
  svelte: ^5.0.0
  svelte-check: ^4.0.0
  sveltekit-superforms: ^2.22.0
  typescript: ^5.7.0
  vite: ^6.0.0
  zod: ^3.24.0

onlyBuiltDependencies:
  - esbuild
